ifneq ($(TARGET_NO_TELEPHONY), true)
ifeq ($(TARGET_FWK_SUPPORTS_FULL_VALUEADDS),true)
ifneq ($(BOARD_IS_AUTOMOTIVE), true)
PRODUCT_PACKAGES += \
                 Mms
endif#BOARD_IS_AUTOMOTIVE
endif#TARGET_FWK_SUPPORTS_FULL_VALUEADDS
endif#TARGET_NO_TELEPHONY
